### ISSUE TITLE
mockup gui for 'print posts'

### ISSUE THREAD

**Issue by elam3** [elam3/Social-Media-Dashboard-in-Java#8]
Hey @tatikozh 

I made a new branch for the GUI version,
https://github.com/elam3/Social-Media-Dashboard-in-Java/tree/mvc_pattern

I'll have to separate the model & view & controls later. But I tried making a draft of what the Post might look like.

**Comment by tatikozh** [comment]
Hey @elam3 

It looks good, I'll play around with it as soon as I get back to States, so Monday and Tuesday I'll be on it.
Thank you
